project_id = "tupzqovgowvwtmrtshdx"

[functions.registrar-log-acesso]
verify_jwt = false

[functions.aprovar-orcamento-publico]
verify_jwt = false

[functions.enviar-email]
verify_jwt = false

[functions.signup-agencia]
verify_jwt = false

[functions.relatorio-semanal]
verify_jwt = false

[functions.asaas-criar-cliente]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-verificar-bloqueio]
verify_jwt = false

[functions.asaas-verificar-pagamento]
verify_jwt = false

[functions.asaas-trocar-pagamento]
verify_jwt = false

[functions.asaas-gerar-qrcode-pix]
verify_jwt = false

[functions.asaas-trocar-plano]
verify_jwt = false

[functions.asaas-verificar-assinatura]
verify_jwt = false

[functions.verificar-status-email]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.asaas-atualizar-cliente]
verify_jwt = false

[functions.whatsapp-criar-instancia]
verify_jwt = false

[functions.whatsapp-status-instancia]
verify_jwt = false

[functions.whatsapp-desconectar]
verify_jwt = false

[functions.whatsapp-enviar-orcamento]
verify_jwt = false

[functions.verificar-orcamentos-expirados]
verify_jwt = false
