-- Add ticket_number auto-incremental column to tickets
ALTER TABLE public.tickets 
ADD COLUMN IF NOT EXISTS ticket_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10001);

-- Create function to generate visual ticket ID (e.g., A#10005)
CREATE OR REPLACE FUNCTION public.ticket_visual_id(_prioridade text, _ticket_number bigint)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path TO public
AS $$
  SELECT UPPER(LEFT(COALESCE(NULLIF(TRIM(_prioridade), ''), 'X'), 1)) || '#' || _ticket_number::text
$$;